### Constants
@host = 192.168.1.104
@port = 8111
@user = admin
@password = admin

### Hardcoded Data
@projectId = project1
@buildTypeId = builtType1
### Get all projects
# @no-cookie-jar
GET http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/roles
Content-Type: application/json
Accept: application/json

### Step 1: create project
# @no-cookie-jar
PUT http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/users/id:57/roles
Content-Type: application/json
Accept: application/json

{
  "role" : [
    {"roleId":"PROJECT_ADMIN","scope":"p:SpringCoreForQa"}
  ]
}



### Step 2: create build type
# @no-cookie-jar
POST http://test_ooosokixAm:test_qpsXHabDqK@{{host}}:{{port}}/app/rest/buildTypes
Content-Type: application/json
Accept: application/json

{
  "id": "test_iTJwAORrsg",
  "name": "test_MKeYzzIPjp",
  "project": {
    "id": "test_nXqWVaDuvY",
    "name": "test_UzEkqtFnSZ"
  },
  "steps": {
    "step": [
      {
        "name": "test_QcEkOePQos",
        "type": "simpleRunner"
      }
    ]
  }
}

### Step 3: run build
# @no-cookie-jar
POST http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/buildQueue
Content-Type: application/json
Accept: application/json

{
  "buildType": {
    "id": "{{buildTypeId}}"
  }
}