name: Run tests

on:
  workflow_call:
    inputs:
      package:
        description: api | ui
        required: true
        type: string

jobs:
  validate-checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'zulu'

      - name: Validate Checkstyle
        run: ./mvnw validate

  run-test:
    needs: validate-checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: TeamCity Setup
        uses: ./.github/actions/teamcity-setup

      - name: Run tests
        continue-on-error: true
        # Указываем группу, чтобы не запустить тесты, связанные с сетапом TeamCity (у них группа Setup)
        run: ./mvnw test -Dtest='com.example.teamcity.${{ inputs.package }}.**' -Dgroups=Regression

      # Создание репорта покрытия API тестов на базе TeamCity Swagger
      # Документация: https://github.com/viclovsky/swagger-coverage
      # Обязательно использовать фильтр SwaggerCoverageRestAssured в RestAssured для подсчета покрытия
      - name: Run Swagger Coverage
        continue-on-error: true
        if: ${{ inputs.package == 'api'}}
        run: .swagger-coverage-commandline/bin/swagger-coverage-commandline -s http://$HOST:8111/app/rest/swagger.json -i target/swagger-coverage-output

      # Сохранение Swagger Report в артефакты GitHub Actions
      - name: Save Swagger Coverage
        uses: actions/upload-artifacts@v4
        if: ${{ inputs.package == 'api'}}
        with:
          name: swagger-coverage
          path: |
            swagger-coverage-report.html
            swagger-coverage-results.json

