name: Deploy frontend

on: workflow_call

# Примерные шаги для развертывания фронтенда
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build frontend
        run: echo Собирается билд фронтенда, запускаются линтеры, выполняются юнит-тесты, формируется и публикуется Docker образ с изменениями

  deploy-stage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend to stage/review app
        run: echo Происходит деплой фронтенда